### ISSUE TITLE
Add a PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by gf712** [samirelanduk/points#2]
To make sure anyone contributing to this project (and any other project) remembers to add tests, or follow any guidelines, you should add a `PULL_REQUEST_TEMPLATE.md` as shown in [here](https://github.com/blog/2111-issue-and-pull-request-templates).

**Comment by samirelanduk** [comment]
Oh I didn't know you could do this - cheers. Will set this up this week.
